sudo: required
language: node_js
node_js:
  - '8'
cache:
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules
    - .meteor/local
before_install:
  - curl https://install.meteor.com | /bin/sh
  - npm install -g mup
stages:
  - name: Test
  - name: Deploy
    if: branch = develop AND type != pull_request
jobs:
  include:
    - stage: Test
      name: Lint
      script: npm run lint
    - stage: Test
      name: Cypress
      script:
        - rm -rf .meteor/local/db
        - MONGO_URL= meteor &
        - sleep 240
        - npm run cypress:run
    - stage: Deploy
      name: Deploy to Staging
      script:
        - cd .deploy
        - mup setup
        - mup deploy --settings .deploy/settings.json --verbose
