sudo: required
language: node_js
node_js:
  - '8'
cache:
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules
    - .meteor/local
stages:
  - name: Test
  - name: Deploy
    if: branch = develop AND type != pull_request
jobs:
  include:
    - stage: Test
      name: Lint
      script: npm run lint
    - stage: Deploy
      name: Deploy to Staging
      script:
        - curl https://install.meteor.com | /bin/sh
        - npm install -g mup
        - cd .deploy
        - mup setup
        - mup deploy --settings settings.json --verbose
